version: '2'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dist
        image: toddlamothe/beerdb-web
        ports:
            - "8002:80"
        networks:
            default:
                external: 
                    name: nat