version: '2'

services:
    api:
        build:
            context: c:\code\beerdb_services\
            dockerfile: Dockerfile
        image: toddlamothe/beerdb-services
        ports:
            - "8888:80"
    web:
        build:
            context: .
            dockerfile: Dockerfile.dist
        image: toddlamothe/beerdb-web
        ports:
            - "8002:80"
networks:
  default:
    external:
      name: nat